language: generic
sudo: required
services: 
  - docker
  

before_install:
  - docker build  -t vjayaram/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true  vjayaram/docker-react npm run test -- --coverage


